---
title: "sharing-release-template"
author: "Rick Gilmore"
date: "`r Sys.time()`"
output: html_document
---

## Databrary Sharing Release Template

Release for [STUDY NAME]

**What we are asking**

This form requests your permission to share material from this session in a secure, web-based data library called Databrary (databrary.org). 
Material from this session may include video/audio recordings, photographs, and images; other information such as age, birth date, sex, ethnicity, education, and self-reported health information; and information supplied by researchers who analyze data from this session. 
The library allows only authorized researchers to have access to shared information. 
Data sharing will lead to faster progress in research on human development and behavior.
In this form, we first request permission to share the data from this session as part of the Databrary library. 
If you agree to share your data, this form also requests permission to allow authorized Databrary researchers to show selected video excerpts and images from recordings of this session for scientific presentations and/or informational and educational purposes, but never for commercial purposes. 
Giving permission to share your information in Databrary is separate from consenting to participate in a research study. 
You do not have to give permission to share your information in the library. 
You can also agree to share your data, but not agree to allow researchers to show excerpts and images. 
Your choices will not affect receipt of payment if offered for participation in this or future studies.

**Will the information be confidential (kept private)?**

No information will be included in the Databrary library about how to contact you or your family. 
No data files will be identified by anyone’s name. 
However, viewers watching or listening to the images and/or voices of people in the recordings may recognize participants if they already know them. 
First and/or last names of people may be spoken aloud. 
If the study takes place in your home, aspects of your home may be seen or heard. 
In addition, other information may have been collected about you, your child, or your family in conjunction with this session. 
Thus, someone who sees the video of this session might be able to identify you, your child, or other people. 
However, all authorized Databrary researchers have agreed to maintain confidentiality and not to reveal the identities of people in the library.

**Who has access to information in the library?**

Only authorized researchers will have access to data in the library. 
Researchers who are granted access must agree to maintain confidentiality and not use information for commercial purposes. 
Researchers promise to treat information in the library with the same high standards of care that they treat information collected in their own laboratories.

**How long will information remain in the library?**

Information in the library will be preserved indefinitely in a secure location so that future researchers can use it. 
Permission to share can be revoked, but information previously shared cannot be retrieved. 
To revoke sharing permission, contact NAME OF PI: CONTACT INFORMATION. 
For questions, contact contact@databrary.org.

**Compensation**

There will be no compensation for sharing information in the library or allowing excerpts to be presented. 

[IF ORAL OR WRITTEN ASSENT TO SHARE DATA IS NEEDED, USE THE FOLLOWING SCRIPT]

Assent to Share Script

Spoken to child by Experimenter:

Earlier, we asked you if you wanted to be in the study and if we could record you while you [describe task]. You said yes.
Right now, only the people who work in this room will see the recordings of you or other information about you from this session. 
We also have the opportunity to put these recordings and other information about you in a secure library so that other scientists who don’t work in this room can also see it. There are many other scientists who want to learn about how children grow and change, but they can’t because they don’t work in this room. 
Is that okay with you?
If you say yes, we will only allow approved scientists to use the library and see the recordings or other information. Your friends, your teachers, and your classmates won’t be able to see them unless you say it is okay.
You can talk this over with your parents before you decide if you want your recordings and other information to be in the library. 
I will also ask your parents to give their permission for your recordings to be in the library, but even if your parents say “yes” you can still say “no” and decide not to put your recordings in the library.
If you don’t want your recordings and other information to be in the library, we don’t have to put them in there. 
Remember, having your recordings and other information in the library is up to you. 
No one will be upset if you don’t want the recordings and other information to be in there.
You can ask any questions that you have about the library. 
If you have a question later that you didn’t think of now, you can call me or ask [your parents, teacher, whoever the child may choose] to call me at [telephone number].

Would you allow your recordings and other information to be stored in the library?

[Participant answers yes or no; only a definite yes may be taken as permission to share.]

ORAL ASSENT: Researcher must record response in signature table and initial.

WRITTEN ASSENT: If you can read and write, and want to have your recordings and other information stored in the library, I can show you the box to check in the signature table.
Would you allow other people besides scientists working in the library to see parts of the recordings?

[Participant answers yes or no; only a definite yes may be taken as permission to share.]

ORAL ASSENT: Researcher must record response in signature table and initial.

WRITTEN ASSENT: If you can read and write, and you want to allow other people to see parts of the recordings, I can show you the box to check in the signature table.

Signatures

All people in the session must decide whether to provide permission for one of the following types of sharing:

**Permission to share with authorized researchers**

I give permission to share the material from this session with authorized researchers in a secure data library called Databrary. 
Authorized researchers may use the material for non-commercial research and educational purposes.

OR

**Permission to share with authorized researchers and show excerpts and images in presentations**

I give permission to share the material from this session with authorized researchers in a secure data library called Databrary. 
Authorized researchers may use the material for non-commercial research and educational purposes.
In addition, I give permission for authorized researchers to show selected excerpts and images as part of presentations that are given in public settings for informational or educational purposes. 
I also understand that at times these presentations may be videotaped or recorded by people who sponsor presentations, and the recordings may be made available to the public via the internet (e.g., YouTube). 
In giving my permission, I trust that authorized researchers will use their professional judgment and uphold ethical principles in determining which excerpts and images to present and to which audiences. 
No one directly associated with this project or the Databrary library will make the contents of this session directly available to the public.
 
We will give you a copy of this form and the signature page for your records. If you have any questions about the data-sharing library, please email contact@databrary.org. For questions about your rights as a research participant, you may contact [APPROPRIATE CONTACT FOR LOCAL INSTITUTION].

By signing below, I indicate that I understand the Databrary Release document and have recorded my own choices for sharing the material from this session in Databrary and allowing authorized Databrary researchers to show excerpts.

ADULTS

|Name |	I give permission to share with authorized researchers |	I give permission to share with authorized researchers and permission to show excerpts and images | Adult’s Signature |	Date|
|---|---|---|---|---|
||	☐ Yes ☐ No	|☐ Yes ☐ No		|||
||	☐ Yes ☐ No	|☐ Yes ☐ No		|||
||	☐ Yes ☐ No	|☐ Yes ☐ No		|||

CHILDREN DECIDING FOR THEMSELVES (ALSO REQUIRES PARENTAL CONSENT)

Researcher must read through Assent to Share Script with those that can provide oral or written assent. Parent or guardian must also decide whether to allow their child to share, and then sign on their behalf.

|Name |	I give permission to share with authorized researchers | I give permission to show excerpts and images |	Participant's Signature |Parent/Guardian Signature |Date|
|---|---|---|---|---|---|
||	☐ Yes ☐ No	|☐ Yes ☐ No		||||	
||	☐ Yes ☐ No	|☐ Yes ☐ No		||||
||	☐ Yes ☐ No	|☐ Yes ☐ No		||||

YOUNG CHILDREN WITH PARENT OR GUARDIAN PROVIDING CONSENT

Parent or guardian must decide whether to allow their child to share and sign on their behalf.

|Name|	I give permission to share with authorized researchers|	I give permission to show excerpts and images|Parent/Guardian Signature|	Date|
|---|---|---|---|---|
|   |	☐ Yes ☐ No	|☐ Yes ☐ No		||  |  
|   | ☐ Yes ☐ No	|☐ Yes ☐ No		|||
|   |	☐ Yes ☐ No	|☐ Yes ☐ No		|||

TO BE COMPLETED BY RESEARCHER OBTAINING PERMISSION

|Researcher’s Name|	I certify that all participants that were recorded have given their decision about whether or not to share with Databrary|Researcher’s Signature|Date|
|---|---|---|---|
||	☐ Yes ☐ No		|||
