---
title: "statement-of-rights"
author: "Rick Gilmore"
date: "`r Sys.time()`"
output: html_document
---

# Annex I -- Statement of Rights and Responsibilities

## Rights Granted to Databrary

Databrary reserves the right to:

-	Redistribute data in Databrary in accordance with the sharing permissions granted by research participants or others whose behaviors are recorded with the permission of Authorized Investigators.
-	Describe, catalog, validate, and document data.
-	Store, translate, copy or re-format data in any way to ensure its future preservation and accessibility.
-	Incorporate metadata or documentation.
-	Promote and advertise data (e.g. via the Databrary newsletter or website) unless specifically prohibited from doing so by an Authorized Investigator or Institution.
- Limit the amount or kind of data stored free of charge or the level of service provided to Authorized Investigators. 
- Give priority for storage and processing resources to data shared with other Authorized Investigators over data stored on Databrary but not shared.
-	Revoke sharing of data that pose a risk of violating confidentiality, harm or embarrass individuals, or create other ethical problems.
- Revoke access to Databrary for ethics violations by any person.
- Remove data and/or deny an Authorized Investigator or Institution access to Databrary, temporarily or permanently, if Databrary determines that the terms of the Databrary Access Agreement are violated.

## Responsibilities of Institutions

The Institution confirms the eligibility of its investigators by:

-	Verifying that its Authorized Investigators are eligible to conduct independent research at the Institution.
-	Verifying that Authorized Investigators who collect or use data from human subjects have completed research ethics training that meets the Institution’s standards concerning policies and protections for human research subjects.
-	Verifying that Authorized Investigators who collect or use data from non-human animal subjects have completed research ethics training that meets the Institution's standards concerning policies and protections for non-human animals.

Further, the Institution agrees that it:

-	Maintains or uses a research ethics board or Institutional Review Board with U.S.-equivalent standards that reviews and approves research involving human subjects.
-	Maintains or uses a research ethics board or Institutional Animal Care and Use Committee with U.S.-equivalent standards to review and approve research involving non-human animal subjects.
-	Grants Authorized Investigators the responsibility to choose and manage Affiliates. 
- Holds Authorized Investigators responsible for the conduct of Affiliates that they select.
-	Accepts responsibility for its Authorized Investigators' actions related to the use of Databrary.

Regarding data contribution and use, the Institution:

-	Asserts that the Authorized Investigator has the right to share with Databrary any data the Authorized Investigator contributes and that no other entity or individual has ownership rights that prevent the Authorized Investigator from contributing data to Databrary.
-	Represents that its Authorized Investigators have the right and authority to store data on Databrary in accordance with any applicable protections set forth by the EU General Data Protection Regulation (GDPR).
-	Represents that it shall follow all applicable laws, including but not limited to the GDPR, in the collection, storage, security, and use of data stored on Databrary.
-	Agrees to allow use of the data exclusively for the purpose of scientific research or education by an academic, research, government, health, or commercial entity.
- Agrees to prohibit commercial uses of data stored on Databrary unless specifically allowed for under the terms of a separate agreement.
-	Agrees not to sell or trade data retrieved from Databrary or use it for other commercial purposes.
-	Grants its Authorized Investigators the authority to decide when and with whom to share data via Databrary.
-	Agrees to inform Databrary of any suspected violation of confidentiality or ethics. 

## Responsibilities of Authorized Investigators

Authorized Investigators agree to adhere to the terms of the **Databrary Access Agreement**, **Annex I -- Statement of Rights and Responsibilities**, and **Annex III -- Databrary Access Guide**.

Authorized Investigators acknowledge and agree to comply with Databrary’s three guiding ethical principles, which are to:

- Treat data stored and shared via Databrary with the same high standards of care that Authorized Investigators treat data collected in their own labs.
- Respect the permissions research participants have given regarding data sharing.
- Take care in granting Affiliates access to Databrary and take responsibility for Affiliates' conduct and use of Databrary.

Additionally, Authorized Investigators agree to:

- Comply with the Institution's policies on the conduct of research.
- Complete training that meets the Institution's standards addressing the ethics of research with human subjects and, as applicable, research with non-human animal subjects.
- Keep contact information and Institutional affiliation information current on Databrary.
- Keep login information confidential and not share it with any other person.
- Cite all Databrary resources used in scholarly work using Databrary’s suggested format or an equivalent.
- Ensure that Affiliates complete training in the ethical use of research data, including the protection of confidentiality, and see to it that Affiliates follow Databrary's ethical principles.
- Secure data downloaded from Databrary with the highest safeguards specified by the Institution's policies concerning sensitive research data.
-	Follow all relevant national, state, and local laws and regulations that pertain to the access, storage, security, and use of human subjects or animal research data.

When contributing data, Authorized Investigators agree to:

- Seek, secure, and maintain permission to conduct research from the entity that governs research at their Institution, and faithfully represent to Databrary information about any research approval status if requested.
- Secure approval from the entity that governs research at the Institution to ask  research participants for permission to share their data in Databrary.
- Ensure that research participants document their permission regarding data sharing by signing documents with Institutionally-approved language comparable to the Databrary Release Template (Annex III) or through other equivalent means.
- Share personally identifiable information with other Authorized Investigators on Databrary no more widely than the data sharing permission given by research participants.
- Provide information to Databrary about the data sharing permission permitted for each data file uploaded to Databrary in accord with the permission granted by research participants.
- Provide licensing information when uploading materials subject to copyright where access should be restricted via a license.
- Exercise professional judgment in determining what to data to store and share on Databrary.
- Store or share with Databrary only those data that the Authorized Investigator has rights to share.
- Assert that no other entity or individual has ownership rights that prevent the Authorized Investigator from contributing data to Databrary.